version: '3.5'
services:

  mysql1:
    image: robinong79/mysql_repl:5.7
    networks:
      - swarm_net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=password1
      - MYSQL_DATABASE=uidb
      - SERVER_ID=1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      placement:
        constraints:
          - node.labels.mysql == true

  mysql2:
    image: robinong79/mysql_repl:5.7
    networks:
      - swarm_net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - SERVER_ID=2
      - AUTO_INIT_MASTER_IP=mysql1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      placement:
        constraints:
          - node.labels.mysql == true

  mysqlfailover:
    image: robinong79/mysqlfailover:1.6.4
    networks:
      - swarm_net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MASTER=mysql1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: none
        max_attempts: 5
      placement:
        constraints:
          - node.labels.mysql == true

  mysqlrouter:
    image: robinong79/mysqlrouter:2.0.4
    ports:
      - 3306:3306
    networks:
      - swarm_net
    environment:
      - MLOGGER_LEVEL=ERROR
      - MYSQLROUTER_BINDPORT=3306
      - DESTINATIONS=mysql1,mysql2
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      placement:
        constraints:
          - node.labels.mysql == true


  redis-master:
    image: dge/redis:5
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.labels.redis-master == true
      restart_policy:
        condition: on-failure
    networks:
      - swarm_net

  redis-slave:
    image: dge/redis:5
    command: --slaveof redis-master 6379
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.labels.redis-replica == true
      restart_policy:
        condition: on-failure
    networks:
      - swarm_net

  redis-sentinel:
    image: dge/redis-sentinel:5
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints:
          - node.labels.redis-sentinel == true
      restart_policy:
        condition: on-failure
    environment:
      - "SENTINEL_MASTER_IP=redis-master"
    networks:
      - swarm_net


networks:
  swarm_net:
    driver: overlay