version: '3.5'
services:

  mysql1:
    image: robinong79/mysql_repl:5.7
    networks:
      - swarm_net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=password1
      - MYSQL_DATABASE=uidb
      - SERVER_ID=1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      placement:
        constraints:
          - node.labels.mysql == true

  mysql2:
    image: robinong79/mysql_repl:5.7
    networks:
      - swarm_net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - SERVER_ID=2
      - AUTO_INIT_MASTER_IP=mysql1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      placement:
        constraints:
          - node.labels.mysql == true

  mysqlfailover:
    image: robinong79/mysqlfailover:1.6.4
    networks:
      - swarm_net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MASTER=mysql1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: none
        max_attempts: 5
      placement:
        constraints:
          - node.labels.mysql == true

  mysqlrouter:
    image: robinong79/mysqlrouter:2.0.4
    ports:
      - 3306:3306
    networks:
      - swarm_net
    environment:
      - MLOGGER_LEVEL=ERROR
      - MYSQLROUTER_BINDPORT=3306
      - DESTINATIONS=mysql1,mysql2
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      placement:
        constraints:
          - node.labels.mysql == true

  redis-master:
    image: dge/redis:5
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.labels.redis-master == true
      restart_policy:
        condition: on-failure
    networks:
      - swarm_net

  redis-slave:
    image: dge/redis:5
    command: --slaveof redis-master 6379
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.labels.redis-replica == true
      restart_policy:
        condition: on-failure
    networks:
      - swarm_net

  redis-sentinel:
    image: dge/redis-sentinel:5
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints:
          - node.labels.redis-sentinel == true
      restart_policy:
        condition: on-failure
    environment:
      - "SENTINEL_MASTER_IP=redis-master"
    networks:
      - swarm_net


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.labels.zookeeper == true
      restart_policy:
        condition: on-failure
    networks:
      - swarm_net

  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    ports:
      - 9094:9094
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.labels.kafka == true
      restart_policy:
        condition: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - swarm_net

  game-master:
    image: dge/game-master:1.0
    ports:
      - 8082:8082
    depends_on:
      - redis-master
      - kafka
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints:
          - node.labels.spring == true
      restart_policy:
        condition: on-failure
    networks:
      - swarm_net

  play-master:
    image: dge/play-master:1.0
    ports:
      - 8081:8081
    depends_on:
      - redis-master
      - kafka
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints:
          - node.labels.spring == true
      restart_policy:
        condition: on-failure
    networks:
      - swarm_net

  user-interface:
    image: dge/user-interface:1.0
    ports:
      - 8080:8080
    depends_on:
      - redis-master
      - kafka
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints:
          - node.labels.spring == true
      restart_policy:
        condition: on-failure
    networks:
      - swarm_net

volumes:
  vol_dbclient:
    driver: local

networks:
  swarm_net:
    driver: overlay