GET http://83.212.102.12:8080/login
Accept: */*
Cache-Control: no-cache

{
  "username": "g12345",
  "password": "g12345"
}


###
GET http://83.212.102.12:8080/user
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1ODY4NjM3ODksImhhc2giOiIzN2QzMWE1MTk5OWY2ODliYmU3ZmQ5NGZiMGQ4Y2FmOSIsInVzZXJuYW1lIjoiZzEyMzQ1In0.APL5ieST3Cp4pFkFarpFVKxGX6Ne1bGMVBEG7-LUYyhFP-2NDzrD_LMHH6UsL_up2Q7sqXjdf7kwMYIkQNX33g
