GET http://localhost:8080/login
Accept: */*
Cache-Control: no-cache

{
  "username": "g12345",
  "password": "g12345"
}


###
GET http://localhost:8080/user
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1ODY5NzkwMDUsImhhc2giOiJkZmM1NWYzZjNiZmQ3NTA0Mjg1NzhmNjg0ZjIzNWU2MiIsInVzZXJuYW1lIjoiZzEyMzQ1In0.AEcxke9BqC9PHDQ-stfRHI6ZkE3ajl2C9D2FNpyPqLUutVjRwYHdGJl1qlYmAwWIsYTPGrxo5lgf-trkZlAf8w


###
GET http://localhost:8082/kafka/status
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1ODY5NzkwMDUsImhhc2giOiJkZmM1NWYzZjNiZmQ3NTA0Mjg1NzhmNjg0ZjIzNWU2MiIsInVzZXJuYW1lIjoiZzEyMzQ1In0.AEcxke9BqC9PHDQ-stfRHI6ZkE3ajl2C9D2FNpyPqLUutVjRwYHdGJl1qlYmAwWIsYTPGrxo5lgf-trkZlAf8w
