GET http://localhost:8080/login
Accept: */*
Cache-Control: no-cache

{
  "username": "g12345",
  "password": "g12345"
}


###
GET http://localhost:8080/user
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1ODY4OTEwOTQsImhhc2giOiIwOTA5NjFkZDk5YWUyMDQzNDUzNGMzYzA4ZTcwNTczMiIsInVzZXJuYW1lIjoiZzEyMzQ1In0.QAhHFKu899yLqWyp-lGqbad3boq6mVCyGoOqsgv-dJYdpTs3GksXcPypxjI89u-RAnAibSRzyYNGEqAK9YYHJA
