POST http://localhost:8080/users/signin?username=admin&password=admin
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/users/user_0001
Accept: */*
Cache-Control: no-cache
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTU4ODA3Nzk2MSwiZXhwIjoxNTg4MDc4MjYxfQ.XKWPGhbPe8lwVmXRAhDysKFckL0Tc5fftU0AucheC5I
###

GET http://localhost:8080/users/refresh
Accept: */*
Cache-Control: no-cache
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTU4ODA3Nzk2MSwiZXhwIjoxNTg4MDc4MjYxfQ.XKWPGhbPe8lwVmXRAhDysKFckL0Tc5fftU0AucheC5I

###

POST http://localhost:8080/users/signup
Content-Type: application/json
Cache-Control: no-cache

{
  "username": "user_0001",
  "password": "password_0001",
  "email": "user_0001@gmail.com",
  "role": "ROLE_CLIENT"
}