GET http://localhost:8081/test/1234
Accept: */*
Cache-Control: no-cache
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTU4NzM4MDI2OSwiZXhwIjoxNTg3MzgwNTY5fQ.vXnA4b5Hus2_iWAc03sQt5aM0T-cdc8EsKlFANNDhs0
